# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_calender(object):
    def setupUi(self, frm_calender):
        frm_calender.setObjectName("frm_calender")
        frm_calender.resize(401, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(frm_calender)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(frm_calender)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)

        self.retranslateUi(frm_calender)
        QtCore.QMetaObject.connectSlotsByName(frm_calender)

    def retranslateUi(self, frm_calender):
        _translate = QtCore.QCoreApplication.translate
        frm_calender.setWindowTitle(_translate("frm_calender", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_calender = QtWidgets.QWidget()
    ui = Ui_frm_calender()
    ui.setupUi(frm_calender)
    frm_calender.show()
    sys.exit(app.exec_())
