# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_new_event.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_dialog_new_event(object):
    def setupUi(self, dialog_new_event):
        dialog_new_event.setObjectName("dialog_new_event")
        dialog_new_event.resize(337, 472)
        self.label = QtWidgets.QLabel(dialog_new_event)
        self.label.setGeometry(QtCore.QRect(40, 70, 101, 21))
        self.label.setStyleSheet("font: 10pt \"Microsoft YaHei\";")
        self.label.setObjectName("label")
        self.txt_event_name = QtWidgets.QLineEdit(dialog_new_event)
        self.txt_event_name.setGeometry(QtCore.QRect(40, 110, 261, 31))
        self.txt_event_name.setText("")
        self.txt_event_name.setObjectName("txt_event_name")
        self.label_2 = QtWidgets.QLabel(dialog_new_event)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 151, 16))
        self.label_2.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_2.setObjectName("label_2")
        self.txt_event_description = QtWidgets.QTextEdit(dialog_new_event)
        self.txt_event_description.setGeometry(QtCore.QRect(40, 190, 261, 131))
        self.txt_event_description.setObjectName("txt_event_description")
        self.txt_location = QtWidgets.QLineEdit(dialog_new_event)
        self.txt_location.setGeometry(QtCore.QRect(40, 360, 261, 31))
        self.txt_location.setText("")
        self.txt_location.setObjectName("txt_location")
        self.label_3 = QtWidgets.QLabel(dialog_new_event)
        self.label_3.setGeometry(QtCore.QRect(40, 330, 91, 16))
        self.label_3.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_3.setObjectName("label_3")
        self.btn_cancel = QtWidgets.QPushButton(dialog_new_event)
        self.btn_cancel.clicked.connect(lambda: dialog_new_event.close())
        self.btn_cancel.setGeometry(QtCore.QRect(30, 410, 121, 41))
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"    font: 10pt \"Microsoft YaHei UI\";\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(228, 196, 255)\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_Create_event = QtWidgets.QPushButton(dialog_new_event)
        self.btn_Create_event.clicked.connect(lambda: self.loadData()) #call load data function
        self.btn_Create_event.setGeometry(QtCore.QRect(180, 410, 121, 41))
        self.btn_Create_event.setStyleSheet("QPushButton{\n"
"    font: 10pt \"Microsoft YaHei UI\";\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(228, 196, 255)\n"
"}\n"
"")
        self.btn_Create_event.setObjectName("btn_Create_event")
        self.dateEdit_event = QtWidgets.QDateEdit(dialog_new_event)
        self.dateEdit_event.setDateTime(QtCore.QDateTime.currentDateTime())#set the dateEdit to current date
        self.dateEdit_event.dateChanged.connect(self.dateEditDateChanged)
        self.dateEdit_event.setGeometry(QtCore.QRect(100, 30, 121, 31))
        self.dateEdit_event.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.dateEdit_event.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_event.setObjectName("dateEdit_event")

        self.retranslateUi(dialog_new_event)
        QtCore.QMetaObject.connectSlotsByName(dialog_new_event)

    def dateEditDateChanged(self):
        #The calendar date was changed
        dateSelected = self.dateEdit_event.date().toPyDate() #format dateSelected to pyDate
       

    #load data into SQLite
    def loadData(self):
        dateSelected = self.dateEdit_event.date().toPyDate()
        weekday =dateSelected.isoweekday() #returns weekday as number (1-7)
        if weekday == 1:
            weekday = 'Monday'
        elif weekday ==2:
            weekday = 'Tuesday'
        elif weekday ==3:
            weekday = 'Wednesday'
        elif weekday ==4:
            weekday = 'Thursday'
        elif weekday ==5:
            weekday = 'Friday'
        elif weekday ==6:
            weekday = 'Saturday'
        elif weekday ==7:
            weekday = 'Sunday'
        
        eventName = self.txt_event_name.text()
        eventDescription = self.txt_event_description.toPlainText()
        location = self.txt_location.text()

        conn = sqlite3.connect("tasks.db")
        cur = conn.cursor()
        user_info = [weekday, eventName, eventDescription, location, dateSelected,]
        cur.execute('INSERT INTO event_info(Weekday, Event_Name, Event_Description, Event_Location, Event_Date) VALUES(?, ?, ?, ?, ?)', user_info)

        conn.commit()
        print('Record inserted successfully')
        conn.close()
    

    def retranslateUi(self, dialog_new_event):
        _translate = QtCore.QCoreApplication.translate
        dialog_new_event.setWindowTitle(_translate("dialog_new_event", "Dialog"))
        self.label.setText(_translate("dialog_new_event", "Event name"))
        self.label_2.setText(_translate("dialog_new_event", "Event description"))
        self.txt_event_description.setHtml(_translate("dialog_new_event", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("dialog_new_event", "Location"))
        self.btn_cancel.setText(_translate("dialog_new_event", "Cancel"))
        self.btn_Create_event.setText(_translate("dialog_new_event", "Create event"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_new_event = QtWidgets.QDialog()
    ui = Ui_dialog_new_event()
    ui.setupUi(dialog_new_event)
    dialog_new_event.show()
    sys.exit(app.exec_())
