# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_addnew.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_addnew(object):
    def setupUi(self, dialog_addnew):
        dialog_addnew.setObjectName("dialog_addnew")
        dialog_addnew.resize(339, 399)
        self.lbl_task_name = QtWidgets.QLineEdit(dialog_addnew)
        self.lbl_task_name.setGeometry(QtCore.QRect(40, 50, 261, 31))
        self.lbl_task_name.setText("")
        self.lbl_task_name.setObjectName("lbl_task_name")
        self.lbl_task_description = QtWidgets.QTextEdit(dialog_addnew)
        self.lbl_task_description.setGeometry(QtCore.QRect(40, 120, 261, 131))
        self.lbl_task_description.setObjectName("lbl_task_description")
        self.label = QtWidgets.QLabel(dialog_addnew)
        self.label.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog_addnew)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog_addnew)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 131, 16))
        self.label_3.setObjectName("label_3")
        self.cb_estimated_time = QtWidgets.QComboBox(dialog_addnew)
        self.cb_estimated_time.setGeometry(QtCore.QRect(190, 270, 121, 22))
        self.cb_estimated_time.setObjectName("cb_estimated_time")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.cb_estimated_time.addItem("")
        self.btn_cancel = QtWidgets.QPushButton(dialog_addnew)
        self.btn_cancel.setGeometry(QtCore.QRect(50, 330, 101, 41))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_Create_task = QtWidgets.QPushButton(dialog_addnew)
        self.btn_Create_task.setGeometry(QtCore.QRect(190, 330, 101, 41))
        self.btn_Create_task.setObjectName("btn_Create_task")

        self.retranslateUi(dialog_addnew)
        QtCore.QMetaObject.connectSlotsByName(dialog_addnew)

    def retranslateUi(self, dialog_addnew):
        _translate = QtCore.QCoreApplication.translate
        dialog_addnew.setWindowTitle(_translate("dialog_addnew", "Dialog"))
        self.lbl_task_description.setHtml(_translate("dialog_addnew", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("dialog_addnew", "Task name"))
        self.label_2.setText(_translate("dialog_addnew", "Task description"))
        self.label_3.setText(_translate("dialog_addnew", "Schedule time blocks:"))
        self.cb_estimated_time.setItemText(0, _translate("dialog_addnew", "15 min"))
        self.cb_estimated_time.setItemText(1, _translate("dialog_addnew", "Estimated time"))
        self.cb_estimated_time.setItemText(2, _translate("dialog_addnew", "30 min"))
        self.cb_estimated_time.setItemText(3, _translate("dialog_addnew", "45 min"))
        self.cb_estimated_time.setItemText(4, _translate("dialog_addnew", "1 hour"))
        self.cb_estimated_time.setItemText(5, _translate("dialog_addnew", "1:30 hours"))
        self.cb_estimated_time.setItemText(6, _translate("dialog_addnew", "2:00 hours"))
        self.cb_estimated_time.setItemText(7, _translate("dialog_addnew", "3:00  hours"))
        self.btn_cancel.setText(_translate("dialog_addnew", "Cancel"))
        self.btn_Create_task.setText(_translate("dialog_addnew", "Create task"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_addnew = QtWidgets.QDialog()
    ui = Ui_dialog_addnew()
    ui.setupUi(dialog_addnew)
    dialog_addnew.show()
    sys.exit(app.exec_())
