# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
# IMPORT FUNCTIONS
from ui_functions import *
#from function_loadData import *
from task_event_window import Ui_SecondWindow
from calendar import Ui_frm_calender
from dialog_addnew import *
import sqlite3


class Ui_MainWindow(object):
    #Open Second Window(choose task or event)
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    #Open calendar widget
    def openWindow2(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_frm_calender()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 552)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("\n"
"background-color: rgb(253, 243, 255);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(249, 242, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #Toggle main pane
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("color: rgb(39, 39, 39);\n"
"border: 0px solid;")
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.frame_top)
        self.frame_2.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        #Add new button. When clicked second window opens.
        self.btn_add_new = QtWidgets.QPushButton(self.frame_2, clicked = lambda:self.openWindow())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_new.sizePolicy().hasHeightForWidth())
        self.btn_add_new.setSizePolicy(sizePolicy)
        self.btn_add_new.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(228, 196, 255)\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_add_new.setObjectName("btn_add_new")
        self.horizontalLayout_4.addWidget(self.btn_add_new)
        self.horizontalLayout_5.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        #Today button. Shows a calender. Shows today's date.
        self.btn_today = QtWidgets.QPushButton(self.frame_3, clicked = lambda:self.openWindow2())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_today.sizePolicy().hasHeightForWidth())
        self.btn_today.setSizePolicy(sizePolicy)
        self.btn_today.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(216, 211, 215);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(216, 211, 215);\n"
"}")
        self.btn_today.setObjectName("btn_today")
        self.verticalLayout_8.addWidget(self.btn_today)
        self.horizontalLayout_5.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(591, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.Content)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_left_menu = QtWidgets.QFrame(self.frame)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(243, 225, 255);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        #Schedule button
        self.btn_menu_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_1.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_1.setCheckable(True)
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.verticalLayout_4.addWidget(self.btn_menu_1)
        #Notes button
        self.btn_menu_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_2.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_2.setCheckable(True)
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.verticalLayout_4.addWidget(self.btn_menu_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        #Logout button
        self.btn_menu_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_menu_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_3.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_menu_3.setObjectName("btn_menu_3")
        self.btn_menu_3.clicked.connect(lambda: MainWindow.close()) #close window
        self.verticalLayout_4.addWidget(self.btn_menu_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus)
        self.horizontalLayout_3.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.frame)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pages_widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.pages_widget.setObjectName("pages_widget")
        self.page_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy)
        self.page_1.setObjectName("page_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.page_1)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        #Sunday table
        self.tbl_sunday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_sunday.setObjectName("tbl_sunday")
        self.tbl_sunday.setColumnCount(1)
        self.tbl_sunday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_sunday.setHorizontalHeaderItem(0, item)
        self.loadSunday()
        self.horizontalLayout_7.addWidget(self.tbl_sunday)

        #Monday table
        self.tbl_monday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_monday.setObjectName("tbl_monday")
        self.tbl_monday.setColumnCount(1)
        self.tbl_monday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_monday.setHorizontalHeaderItem(0, item)
        self.loadMonday()
        self.horizontalLayout_7.addWidget(self.tbl_monday)

        #Tuesday table
        self.tbl_tuesday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_tuesday.setObjectName("tbl_tuesday")
        self.tbl_tuesday.setColumnCount(1)
        self.tbl_tuesday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_tuesday.setHorizontalHeaderItem(0, item)
        self.loadTuesday()
        self.horizontalLayout_7.addWidget(self.tbl_tuesday)

        #Wednesday table
        self.tbl_wednesday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_wednesday.setObjectName("tbl_wednesday")
        self.tbl_wednesday.setColumnCount(1)
        self.tbl_wednesday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_wednesday.setHorizontalHeaderItem(0, item)
        self.loadWednesday()
        self.horizontalLayout_7.addWidget(self.tbl_wednesday)

        #Thursday table
        self.tbl_thursday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_thursday.setObjectName("tbl_thursday")
        self.tbl_thursday.setColumnCount(1)
        self.tbl_thursday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_thursday.setHorizontalHeaderItem(0, item)
        self.loadThursday()
        self.horizontalLayout_7.addWidget(self.tbl_thursday)

        #Friday Table
        self.tbl_friday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_friday.setObjectName("tbl_friday")
        self.tbl_friday.setColumnCount(1)
        self.tbl_friday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_friday.setHorizontalHeaderItem(0, item)
        self.loadFriday()
        self.horizontalLayout_7.addWidget(self.tbl_friday)

        #Saturday table
        self.tbl_saturday = QtWidgets.QTableWidget(self.frame_7)
        self.tbl_saturday.setObjectName("tbl_saturday")
        self.tbl_saturday.setColumnCount(1)
        self.tbl_saturday.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_saturday.setHorizontalHeaderItem(0, item)
        self.loadSaturday()
        self.horizontalLayout_7.addWidget(self.tbl_saturday)

        self.verticalLayout_6.addWidget(self.frame_7)
        self.pages_widget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        #notes table
        self.tbl_notes_display = QtWidgets.QTableWidget(self.frame_5)
        self.tbl_notes_display.setObjectName("tbl_notes_display")
        self.tbl_notes_display.setColumnCount(0)
        self.tbl_notes_display.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tbl_notes_display)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        #new note button
        self.btn_new_note = QtWidgets.QPushButton(self.frame_6)
        self.btn_new_note.setGeometry(QtCore.QRect(650, 20, 98, 38))
        self.btn_new_note.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(243, 225, 255);\n"
"    border: 0px solid\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(228, 196, 255)\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.btn_new_note.setObjectName("btn_new_note")
        #Text area for notes
        self.txt_notes = QtWidgets.QTextEdit(self.frame_6)
        self.txt_notes.setGeometry(QtCore.QRect(0, 0, 771, 511))
        self.txt_notes.setObjectName("txt_notes")
        self.txt_notes.raise_()
        self.btn_new_note.raise_()
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.pages_widget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.pages_widget)
        self.horizontalLayout_3.addWidget(self.frame_pages)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ## TOGGLE/BURGER MENU
        self.btn_toggle.clicked.connect(lambda: UIFunctions.toggleMenu(self, 250, True))

        ## PAGES

        # PAGE 1
        self.btn_menu_1.clicked.connect(lambda: self.pages_widget.setCurrentWidget(self.page_1))
        # PAGE 2
        self.btn_menu_2.clicked.connect(lambda: self.pages_widget.setCurrentWidget(self.page_2))

    def loadSunday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Sunday';"

        self.tbl_sunday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_sunday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadMonday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Monday';"
        self.tbl_monday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_monday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadTuesday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Tuesday';"
        self.tbl_tuesday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_tuesday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadWednesday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Wednesday';"
        self.tbl_wednesday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_wednesday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadThursday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Thursday';"
        self.tbl_thursday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_thursday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadFriday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Friday';"
        self.tbl_friday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_friday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
    def loadSaturday(self):
        connection = sqlite3.connect("tasks.db")
        cur = connection.cursor()
        sqlquery = "Select Task_Name FROM task_info WHERE Weekday = 'Saturday';"
        self.tbl_saturday.setRowCount(7)
        tablerow = 0
        for row in cur.execute(sqlquery):
                self.tbl_saturday.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                tablerow +=1
                
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_toggle.setText(_translate("MainWindow", "MENU"))
        self.btn_add_new.setText(_translate("MainWindow", "Add New+"))
        self.btn_today.setText(_translate("MainWindow", "Today"))
        self.btn_menu_1.setText(_translate("MainWindow", "Schedule"))
        self.btn_menu_2.setText(_translate("MainWindow", "Notes"))
        self.btn_menu_3.setText(_translate("MainWindow", "Logout"))
        item = self.tbl_sunday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sunday"))
        item = self.tbl_monday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Monday"))
        item = self.tbl_tuesday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tuesday"))
        item = self.tbl_wednesday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Wednesday"))
        item = self.tbl_thursday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thursday"))
        item = self.tbl_friday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Friday"))
        item = self.tbl_saturday.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Saturday"))
        self.btn_new_note.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
